### ISSUE TITLE
How can your access to session data typescript compile...

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [arbassic/ts-sequelize-example#3]
Hi @arbassic  , thank you for publishing your example.

I am working with node/typescript and express

I looked up desperately google and github, to find a way to read/write data to my http session (I am using package `express-session`, like you and many) : 
* when I `console.log(req.session)`, I see data like : 

```bash 

---------------------------------------
 Express Session is : 
Session {
  cookie: { path: '/', _expires: null, originalMaxAge: null, httpOnly: true },
  passport: {
    user: {
      github_profile: [Object],
      github_access_token: '9838d3c2a8817e393fa673d43f70b602b2a9bdc8'
    }
  }
}
---------------------------------------
^C
jbl@poste-devops-jbl-16gbram:~/hugo-cheatsheet$ tsc
src/server/permissions/pokus/github/index.ts:29:31 - error TS2339: Property 'passport' does not exist on type 'Session & Partial<SessionData>'.

29       console.log(req.session.passport)
                                 ~~~~~~~~


Found 1 error.

```

* and in `TypeScript`, as you can see, If  I try to `req.session.passport` or `req.session["passport"]`, then my compiler of course gives me an error...
* How can I access those properties which **I know** are there, really could not find one example anywhere... 
* and even worse : I git cloned you project, and it perfectly compiles!... I have same `tsconfig.json` than you in my project! .... This is killing me ...  
* Was hoping with your nice work here,you could tell me what am I doing wrong, here...

Here is my source code : 
* here (commented) the line that does not compile : https://github.com/pokusio/hugo-cheatsheet/blob/620226c5c33b56a88330b66582dfd88975d0a611/src/server/permissions/pokus/github/index.ts#L29

Would you have any tip on how to do that ..?

**Comment by Jean-Baptiste-Lasselle** [comment]
sorry for the disturbance, I managed to find a workaround

**Comment by arbassic** [comment]
I think the best solution is to provide an additional file with app-related types (include that file in tsconfig.json) and there define the session structure. I did that kind of thing in another project - worked perfectly 👌🏻 


Example definition:


```
declare global {
  namespace Express {
    interface Session {
      userHash: string;
      privileges: string[];
      login: string;
    }
  }
}
```
